title: "Núria Ribas Costa"
description: "Nuria Ribas Costa is a Spanish Journalist and Jurist based between Rotterdam and Ibiza, her homeland."
markdown: kramdown

baseurl: ""
url: "https://nuriaribascosta.eu"

permalink: pretty
plugins: []
